function Gui()
%GUI -
    antennaType = 'Izotropică';
    sc_handle   = [];

    % ---- Figura principala ----
    hFig = figure( ...
        'Name',        'Satellite Communications for ADS-B Out', ...
        'NumberTitle', 'off', ...
        'Position',    [40, 40, 1280, 760], ...
        'Color',       [0.13 0.13 0.13], ...
        'Resize',      'on');
    hFig.CloseRequestFcn = @(~,~) delete(hFig);


    % PANEL STANG

    pL = uipanel(hFig, ...
        'Title',           'Parametri de Intrare', ...
        'Units',           'normalized', ...
        'Position',        [0.005 0.01 0.275 0.98], ...
        'BackgroundColor', [0.18 0.18 0.18], ...
        'ForegroundColor', [0.90 0.90 0.90], ...
        'FontSize',        10, ...
        'FontWeight',      'bold');

    % Frecventa ADS-B (informativ, linie unica)
    uicontrol(pL,'Style','text','String','Frecvență ADS-B', ...
        'Units','normalized','Position',[0.05 0.924 0.56 0.038], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.58 0.58 0.58], ...
        'HorizontalAlignment','left','FontSize',9);
    uicontrol(pL,'Style','text','String','1090 MHz', ...
        'Units','normalized','Position',[0.61 0.924 0.34 0.038], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.20 0.85 0.20], ...
        'HorizontalAlignment','right','FontSize',9,'FontWeight','bold');

    % Separator subtire
    uicontrol(pL,'Style','text','String','', ...
        'Units','normalized','Position',[0.05 0.916 0.90 0.004], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Tip antena - eticheta
    uicontrol(pL,'Style','text','String','Tip Antenă pe Satelit:', ...
        'Units','normalized','Position',[0.05 0.876 0.90 0.036], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.90 0.90 0.90], ...
        'HorizontalAlignment','left','FontSize',9,'FontWeight','bold');

    % Dropdown tip antena
    ddAntenna = uicontrol(pL, ...
        'Style',           'popupmenu', ...
        'String',          {'Izotropică','48 Fascicule Personalizate (Phased Array)'}, ...
        'Units',           'normalized', ...
        'Position',        [0.05 0.815 0.90 0.055], ...
        'BackgroundColor', [0.28 0.28 0.28], ...
        'ForegroundColor', [0.95 0.95 0.95], ...
        'FontSize',        9, ...
        'Callback',        @cbAntennaChange);

    % Caracteristici antena - eticheta
    uicontrol(pL,'Style','text','String','Caracteristici Antenă:', ...
        'Units','normalized','Position',[0.05 0.778 0.90 0.030], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.55 0.55 0.55], ...
        'HorizontalAlignment','left','FontSize',8);

    % Listbox readonly
    lstCaract = uicontrol(pL, ...
        'Style',           'listbox', ...
        'String',          getAntennaCharacteristics('Izotropică'), ...
        'Units',           'normalized', ...
        'Position',        [0.05 0.570 0.90 0.204], ...
        'BackgroundColor', [0.22 0.22 0.22], ...
        'ForegroundColor', [0.72 0.94 0.72], ...
        'FontSize',        8, ...
        'Enable',          'inactive');

    % Separator
    uicontrol(pL,'Style','text','String','', ...
        'Units','normalized','Position',[0.05 0.562 0.90 0.004], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Stare - eticheta + casuta separata
    uicontrol(pL,'Style','text','String','Stare:', ...
        'Units','normalized','Position',[0.05 0.532 0.90 0.026], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.52 0.52 0.52], ...
        'HorizontalAlignment','left','FontSize',8,'FontWeight','bold');
    hStatus = uicontrol(pL,'Style','text','String','Gata!', ...
        'Units','normalized','Position',[0.05 0.470 0.90 0.058], ...
        'BackgroundColor',[0.21 0.21 0.21],'ForegroundColor',[0.20 0.85 0.20], ...
        'HorizontalAlignment','center','FontSize',9,'FontWeight','bold');

    % Separator
    uicontrol(pL,'Style','text','String','', ...
        'Units','normalized','Position',[0.05 0.462 0.90 0.004], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Sectiune Actiuni
    uicontrol(pL,'Style','text','String','ACȚIUNI', ...
        'Units','normalized','Position',[0.05 0.426 0.90 0.030], ...
        'BackgroundColor',[0.18 0.18 0.18],'ForegroundColor',[0.65 0.65 0.65], ...
        'HorizontalAlignment','left','FontSize',9,'FontWeight','bold');
    uicontrol(pL,'Style','text','String','', ...
        'Units','normalized','Position',[0.05 0.419 0.90 0.004], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Buton Ruleaza Simularea
    btnRun = uicontrol(pL, ...
        'Style','pushbutton','String','RULEAZĂ SIMULAREA', ...
        'Units','normalized','Position',[0.05 0.316 0.90 0.096], ...
        'BackgroundColor',[0.16 0.46 0.80],'ForegroundColor','white', ...
        'FontSize',10,'FontWeight','bold','Callback',@(~,~) cbRunSim());

    % Buton Deschide Documentatie
    uicontrol(pL, ...
        'Style','pushbutton','String','Deschide Documentația', ...
        'Units','normalized','Position',[0.05 0.204 0.90 0.096], ...
        'BackgroundColor',[0.42 0.22 0.60],'ForegroundColor','white', ...
        'FontSize',10,'FontWeight','bold','Callback',@(~,~) cbOpenDoc());

    % Buton Reset
    uicontrol(pL, ...
        'Style','pushbutton','String','Resetează', ...
        'Units','normalized','Position',[0.05 0.092 0.90 0.096], ...
        'BackgroundColor',[0.58 0.20 0.16],'ForegroundColor','white', ...
        'FontSize',10,'FontWeight','bold','Callback',@(~,~) cbReset());


    % PANEL DREAPTA

    pR = uipanel(hFig, ...
        'Title',           'Rezultate', ...
        'Units',           'normalized', ...
        'Position',        [0.285 0.01 0.710 0.98], ...
        'BackgroundColor', [0.13 0.13 0.13], ...
        'ForegroundColor', [0.90 0.90 0.90], ...
        'FontSize',        10, ...
        'FontWeight',      'bold');

    % Titlu sectiune antena (cu tipul curent)
    hLblAntenna = uicontrol(pR,'Style','text', ...
        'String','Model Radiație Antenă  |  Izotropică', ...
        'Units','normalized','Position',[0.02 0.963 0.96 0.030], ...
        'BackgroundColor',[0.13 0.13 0.13],'ForegroundColor',[0.95 0.95 0.95], ...
        'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');

    % Axe diagrama antena (3D)
    axAntenna = axes('Parent',pR, ...
        'Units','normalized','Position',[0.10 0.535 0.80 0.418], ...
        'Color',[0.09 0.09 0.09], ...
        'XColor',[0.60 0.60 0.60],'YColor',[0.60 0.60 0.60],'ZColor',[0.60 0.60 0.60], ...
        'GridColor',[0.32 0.32 0.32],'GridAlpha',0.5);

    % Separator orizontal
    uicontrol(pR,'Style','text','String','', ...
        'Units','normalized','Position',[0.02 0.485 0.96 0.003], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Titlu sectiune Bilant Legatura (stanga jos, updateabil)
    hLblLink = uicontrol(pR,'Style','text', ...
        'String','Bilanț de Legătură', ...
        'Units','normalized','Position',[0.01 0.448 0.47 0.033], ...
        'BackgroundColor',[0.13 0.13 0.13],'ForegroundColor',[0.95 0.95 0.95], ...
        'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');

    % Axe Bilant Legatura (2D, stanga jos)
    axLink = axes('Parent',pR, ...
        'Units','normalized','Position',[0.07 0.058 0.41 0.384], ...
        'Color',[0.09 0.09 0.09], ...
        'XColor',[0.60 0.60 0.60],'YColor',[0.60 0.60 0.60], ...
        'GridColor',[0.32 0.32 0.32],'GridAlpha',0.5);
    xlabel(axLink,'Timp','Color',[0.60 0.60 0.60],'FontSize',9);
    ylabel(axLink,'Bilanț (dB)','Color',[0.60 0.60 0.60],'FontSize',9);
    text(0.5, 0.5, 'RULAȚI SIMULAREA pentru a vedea rezultatele...', ...
        'Units','normalized','HorizontalAlignment','center', ...
        'Color',[0.45 0.45 0.45],'FontSize',9,'Parent',axLink);
    grid(axLink,'on');

    % Separator vertical intre Bilant Legatura si Vizibilitate Sateliti
    uicontrol(pR,'Style','text','String','', ...
        'Units','normalized','Position',[0.494 0.018 0.003 0.462], ...
        'BackgroundColor',[0.35 0.35 0.35]);

    % Titlu sectiune Vizibilitate Sateliti (dreapta jos)
    hLblVis = uicontrol(pR,'Style','text', ...
        'String','Vizibilitate Sateliți', ...
        'Units','normalized','Position',[0.51 0.448 0.47 0.033], ...
        'BackgroundColor',[0.13 0.13 0.13],'ForegroundColor',[0.95 0.95 0.95], ...
        'HorizontalAlignment','center','FontSize',10,'FontWeight','bold');

    % Axe Vizibilitate Sateliti 
    axVis = axes('Parent',pR, ...
        'Units','normalized','Position',[0.58 0.058 0.38 0.384], ...
        'Color',[0.09 0.09 0.09], ...
        'XColor',[0.60 0.60 0.60],'YColor',[0.60 0.60 0.60], ...
        'GridColor',[0.32 0.32 0.32],'GridAlpha',0.5);
    xlabel(axVis,'Timp','Color',[0.60 0.60 0.60],'FontSize',9);
    text(0.5, 0.5, 'Rulați simularea pentru a vedea rezultatele', ...
        'Units','normalized','HorizontalAlignment','center', ...
        'Color',[0.45 0.45 0.45],'FontSize',9,'Parent',axVis);
    grid(axVis,'on');

    % Afisam diagrama antena initiala
    plotAntennaPattern(axAntenna, 'Izotropică');


    % FUNCTII IMBRICATE
    function cbAntennaChange(src, ~)
        types = {'Izotropică','48 Fascicule Personalizate (Phased Array)'};
        antennaType = types{src.Value};
        hLblAntenna.String = ['Model Radiație Antenă  |  ' antennaType];
        plotAntennaPattern(axAntenna, antennaType);
        lstCaract.String = getAntennaCharacteristics(antennaType);
        setStatus('Antenă schimbată. Rulați simularea.', [0.92 0.70 0.10]);
    end

    function cbRunSim()
        btnRun.Enable = 'off';
        setStatus('Se construiește scenariul ...', [0.92 0.70 0.10]);
        drawnow;
        try
            [sc, aircraft, iridiumSats, iridiumConicalSensors, txADSB, rxAirport] = buildScenario();
            sc_handle = sc;

            % Cream viewer-ul explicit si centram camera pe avion de la
            % inceput
            viewer = satelliteScenarioViewer(sc);
            camtarget(viewer, aircraft);

            fADSB = 1090e6;
            setStatus('Se configurează antena satelit ...', [0.92 0.70 0.10]);
            drawnow;

            if strcmp(antennaType, 'Izotropică')
                satAnt = arrayConfig("Size",[1 1]);
                rxSat  = receiver(iridiumSats, ...
                    Antenna=satAnt, MountingAngles=[0,0,0], ...
                    Name=iridiumSats.Name + " Receptor");
                pattern(rxSat, fADSB, Size=50000);
            else
                satAnt = HelperCustom48BeamAntenna(fADSB);
                rxSat  = receiver(iridiumSats, ...
                    Antenna=satAnt, MountingAngles=[0,-90,0], ...
                    Name=iridiumSats.Name + " Receptor");
                pattern(rxSat, fADSB, Size=200000);
            end

            % Bilant Legatura - o singura calculare
            setStatus('Se calculează Bilanțul de Legătură ...', [0.92 0.70 0.10]);
            drawnow;
            lnk      = link(txADSB, [rxAirport, rxSat]);
            [eL, t]  = ebno(lnk);
            marg     = eL - repmat([rxAirport.RequiredEbNo, rxSat.RequiredEbNo]', ...
                           [1, size(eL,2)]);

            % Afisam rezultat in axe
            cla(axLink);
            plot(axLink, t, max(marg), 'Color',[0.20 0.60 1.00], 'LineWidth',1.5);
            axis(axLink,'tight');
            grid(axLink,'on');
            xlabel(axLink,'Timp','Color',[0.60 0.60 0.60],'FontSize',9);
            ylabel(axLink,'Marjă (dB)','Color',[0.60 0.60 0.60],'FontSize',9);
            axLink.Color     = [0.09 0.09 0.09];
            axLink.XColor    = [0.60 0.60 0.60];
            axLink.YColor    = [0.60 0.60 0.60];
            axLink.GridColor = [0.32 0.32 0.32];
            hLblLink.String  = ['Bilanț Legătură  |  ' antennaType '  -  Marjă ADS-B Out'];

            % Vizibilitate sateliti
            setStatus('Se calculează vizibilitatea sateliților ...', [0.92 0.70 0.10]);
            drawnow;
            acSatellite = access(aircraft, iridiumConicalSensors);
            [sSatellite, timeVis] = accessStatus(acSatellite);
            satVisData = double(sSatellite);
            satVisData(satVisData == 0) = NaN;
            satVisData = satVisData + (0:numel(iridiumSats)-1)';
            cla(axVis);
            plot(axVis, timeVis, satVisData, '.', 'Color', [0.20 0.60 1.00], 'MarkerSize', 4);
            yticks(axVis, 1:5:66);
            yticklabels(axVis, iridiumSats.Name(1:5:66));
            axis(axVis, 'tight');
            grid(axVis, 'on');
            xlabel(axVis, 'Timp', 'Color', [0.60 0.60 0.60], 'FontSize', 9);
            axVis.Color     = [0.09 0.09 0.09];
            axVis.XColor    = [0.60 0.60 0.60];
            axVis.YColor    = [0.60 0.60 0.60];
            axVis.GridColor = [0.32 0.32 0.32];
            axVis.FontSize  = 7;

            setStatus('Gata! Se lansează vizualizatorul ...', [0.18 0.85 0.18]);
            drawnow;

            % O singura lansare a scenariului principal
            play(sc);

        catch ME
            setStatus(['Eroare: ' ME.message], [0.90 0.18 0.18]);
            warning(ME.identifier, '%s', ME.message);
        end
        btnRun.Enable = 'on';
    end

    function cbOpenDoc()
        docPath = fullfile(fileparts(mfilename('fullpath')), 'Proiect RC.docx');
        if ~isfile(docPath)
            errordlg(['Fișierul nu a fost găsit:' newline docPath], ...
                'Eroare documentație');
            return;
        end
        try
            if ispc
                winopen(docPath);
            elseif ismac
                system(['open "' docPath '" &']);
            else
                system(['xdg-open "' docPath '" &']);
            end
        catch
            errordlg('Nu s-a putut deschide documentul Word.', 'Eroare');
        end
    end

    function cbReset()
        antennaType        = 'Izotropică';
        sc_handle          = [];
        ddAntenna.Value    = 1;
        lstCaract.String   = getAntennaCharacteristics('Izotropică');
        hLblAntenna.String = 'Model Radiație Antenă  |  Izotropică';
        hLblLink.String    = 'Bilanț Legătură  |  Marjă ADS-B Out vs. Timp';
        cla(axLink);
        xlabel(axLink,'Timp','Color',[0.60 0.60 0.60],'FontSize',9);
        ylabel(axLink,'Marjă (dB)','Color',[0.60 0.60 0.60],'FontSize',9);
        text(0.5, 0.5, 'Rulați simularea pentru a vedea rezultatele', ...
            'Units','normalized','HorizontalAlignment','center', ...
            'Color',[0.45 0.45 0.45],'FontSize',9,'Parent',axLink);
        grid(axLink,'on');
        axLink.Color     = [0.09 0.09 0.09];
        axLink.XColor    = [0.60 0.60 0.60];
        axLink.YColor    = [0.60 0.60 0.60];
        axLink.GridColor = [0.32 0.32 0.32];
        plotAntennaPattern(axAntenna, 'Izotropică');
        cla(axVis);
        text(0.5, 0.5, 'Rulați simularea pentru a vedea rezultatele', ...
            'Units','normalized','HorizontalAlignment','center', ...
            'Color',[0.45 0.45 0.45],'FontSize',9,'Parent',axVis);
        grid(axVis,'on');
        axVis.Color     = [0.09 0.09 0.09];
        axVis.XColor    = [0.60 0.60 0.60];
        axVis.YColor    = [0.60 0.60 0.60];
        axVis.GridColor = [0.32 0.32 0.32];
        setStatus('Resetat.', [0.18 0.85 0.18]);
    end

    function setStatus(msg, col)
        hStatus.String          = msg;
        hStatus.ForegroundColor = col;
        drawnow;
    end

end  % end Gui()

%  buildScenario  -  Construieste scenariul satelit fara play()

function [sc, aircraft, iridiumSatellites, iridiumConicalSensors, txADSB, rxAirport] = buildScenario()
    startTime  = datetime(2026,4,9,15,55,0, TimeZone="Pacific/Auckland");
    stopTime   = startTime + hours(3) + minutes(50);
    sampleTime = 10;
    sc = satelliteScenario(startTime, stopTime, sampleTime);

    airportName = ["Aeroportul Internațional Wellington (Wellington)"; ...
                   "Aeroportul Kingsford Smith Sydney (Sydney)"];
    airportLat  = [-41.3272; -33.9548];
    airportLon  = [174.8052; 151.1897];
    airports    = groundStation(sc, airportLat, airportLon, Name=airportName);

    waypoints = [ ...
        -41.3272, 174.8052,    4; -41.4088, 174.7811,  609; ...
        -41.4424, 174.7494, 1219; -41.4298, 174.6538, 1828; ...
        -41.0500, 173.1000, 5500; -40.5500, 171.5000, 9000; ...
        -40.0000, 170.0000,11582; -39.2000, 167.0000,11582; ...
        -38.4000, 164.1000,11582; -37.5000, 161.1000,11582; ...
        -36.7000, 158.2000,11582; -35.9324, 155.2361,11582; ...
        -35.3403, 154.2447,11582; -35.1915, 153.9896,11277; ...
        -35.0398, 153.7313,11277; -34.8009, 153.3287,10500; ...
        -34.3358, 152.5571, 8229; -34.0329, 152.0384, 5181; ...
        -34.0017, 151.8044, 3657; -33.7669, 151.4050, 1524; ...
        -33.7430, 151.1863,  914; -33.7626, 151.1639,  914; ...
        -33.9548, 151.1897,    6];

    timeOfArrival = duration([ ...
        "00:00:00";"00:00:25";"00:01:05";"00:02:00";"00:05:30";"00:12:00"; ...
        "00:21:00";"00:41:00";"01:01:00";"01:21:00";"01:41:00";"02:01:00"; ...
        "02:10:00";"02:14:00";"02:18:00";"02:22:00";"02:29:00";"02:35:00"; ...
        "02:39:00";"02:43:00";"02:47:00";"02:50:00";"02:55:00"]);

    trajectory = geoTrajectory(waypoints, seconds(timeOfArrival), ...
        AutoPitch=true, AutoBank=true);
    aircraft = platform(sc, trajectory, Name="Avion", ...
        Visual3DModel="NarrowBodyAirliner.glb");

    % Constelatie Iridium NEXT - 66 sateliti, 6 plane orbitale
    numSatsPerPlane = 11;
    numOrbits       = 6;
    orbitIdx  = repelem(1:numOrbits, 1, numSatsPerPlane);
    planeIdx  = repmat(1:numSatsPerPlane, 1, numOrbits);
    RAAN      = 180*(orbitIdx-1)/numOrbits;
    trueanom  = 360*(planeIdx-1 + 0.5*(mod(orbitIdx,2)-1))/numSatsPerPlane;
    sma       = repmat((6371+780)*1e3, size(RAAN));

    iridiumSatellites = satellite(sc, sma, zeros(size(RAAN)), ...
        repmat(86.4,size(RAAN)), RAAN, zeros(size(RAAN)), trueanom, ...
        Name="Iridium " + string(1:66)');

    iridiumConicalSensors = conicalSensor(iridiumSatellites, "MaxViewAngle", 125);

    fADSB  = 1090e6;
    txAnt  = arrayConfig("Size",[1 1]);
    txADSB = transmitter(aircraft, ...
        Antenna=txAnt, Frequency=fADSB, Power=10*log10(125), ...
        MountingLocation=[8,0,-2.7], Name="Emițător ADS-B Avion");

    rxAnt     = arrayConfig("Size",[1 1]);
    rxAirport = receiver(airports, Antenna=rxAnt, Name=airports.Name + " Receptor");
    pattern(rxAirport, fADSB, Size=1000);
end



%  plotAntennaPattern  -  Deseneaza diagrama de radiatie 3D
%  Titlul sectiunii este gestionat de uicontrol extern (hLblAntenna).
%
function plotAntennaPattern(ax, antennaType)
    cla(ax);
    if strcmp(antennaType, 'Izotropică')
        [X,Y,Z] = sphere(80);
        G = zeros(size(X));
        surf(ax, X, Y, Z, G, 'EdgeColor','none', 'FaceAlpha',0.80);
        colormap(ax, parula);
        cb = colorbar(ax);
        ylabel(cb,'Câștig (dBi)');
        cb.Color = [0.62 0.62 0.62];
        axis(ax,'equal');
        view(ax, 3);
    else
        az = linspace(-pi, pi, 361);
        el = linspace(-pi/2, pi/2, 181);
        [AZ,EL] = meshgrid(az, el);
        Gpeak  = 24;
        bwHalf = 4*pi/180;
        bDirs  = generateBeamDirections(48);
        G      = -35*ones(size(AZ));
        for k = 1:size(bDirs,1)
            az0 = bDirs(k,1);
            el0 = bDirs(k,2);
            ang = acos(max(-1, min(1, ...
                cos(EL).*cos(AZ-az0).*cos(el0) + sin(EL).*sin(el0))));
            Gk  = Gpeak - 12*(ang./bwHalf).^2;
            G   = max(G, Gk);
        end
        Rn = max(G - min(G(:)), 0);
        Xp = Rn.*cos(EL).*cos(AZ);
        Yp = Rn.*cos(EL).*sin(AZ);
        Zp = Rn.*sin(EL);
        surf(ax, Xp, Yp, Zp, G, 'EdgeColor','none', 'FaceAlpha',0.88);
        colormap(ax, jet);
        cb = colorbar(ax);
        ylabel(cb,'Câștig (dBi)');
        cb.Color = [0.62 0.62 0.62];
        axis(ax,'equal');
        view(ax, [-35 25]);
    end
    xlabel(ax,'X','Color',[0.60 0.60 0.60]);
    ylabel(ax,'Y','Color',[0.60 0.60 0.60]);
    zlabel(ax,'Z','Color',[0.60 0.60 0.60]);
    grid(ax,'on');
    ax.Color     = [0.09 0.09 0.09];
    ax.XColor    = [0.60 0.60 0.60];
    ax.YColor    = [0.60 0.60 0.60];
    ax.ZColor    = [0.60 0.60 0.60];
    ax.GridColor = [0.32 0.32 0.32];
end

%  generateBeamDirections  -  Distributie Fibonacci pe sfera (N directii)

function dirs = generateBeamDirections(N)
    golden = (1 + sqrt(5)) / 2;
    i   = (0:N-1)';
    el  = asin(2*i/N - 1);
    az  = mod(2*pi*i/golden, 2*pi) - pi;
    dirs = [az, el];
end

%  getAntennaCharacteristics  -  Returneaza caracteristicile antenei selectate
function lines = getAntennaCharacteristics(antennaType)
    if strcmp(antennaType, 'Izotropică')
        lines = { ...
            'Tip:         Antenă Izotropică', ...
            'Câștig:      0 dBi (uniform)', ...
            'Radiere:     Sferică, Toate Direcțiile', ...
            'Montaj:      [0, 0, 0] grade', ...
            'Frecvență:   1090 MHz (ADS-B)', ...
            'Putere TX:   125 W ', ...
            'Utilizare:   Model Simplificat'};
    else
        lines = { ...
            'Tip:         Phased Array 48 Fascicule', ...
            'Câștig max:  ~24 dBi / fascicul', ...
            'Fascicule:   48 spot beams', ...
            'Lățime fasc: ~8 grade (HPBW)', ...
            'Acoperire:   ~125 grade-conic', ...
            'Montare:     [0, -90, 0] grade', ...
            'Frecvență:   1090 MHz (ADS-B)', ...
            'Utilizare:   Model real Iridium NEXT'};
    end
end
